

-- TẠO CƠ SỞ DỮ LIỆU MỚI
CREATE DATABASE QUANLYQUANCAPHE
GO

USE QUANLYQUANCAPHE
GO

-- Bảng 1: LOAITAIKHOAN
CREATE TABLE LOAITAIKHOAN
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL
)
GO

-- Bảng 2: TAIKHOAN
CREATE TABLE TAIKHOAN
(
    TenDangNhap VARCHAR(100) PRIMARY KEY,
    MatKhau NVARCHAR(1000) NOT NULL,
    TenHienThi NVARCHAR(100) NOT NULL,
    IDLoaiTaiKhoan INT NOT NULL,
    FOREIGN KEY (IDLoaiTaiKhoan) REFERENCES dbo.LOAITAIKHOAN(ID)
)
GO

-- Bảng 3: NHANVIEN
CREATE TABLE NHANVIEN
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) UNIQUE,
    TenDangNhap VARCHAR(100) NOT NULL UNIQUE,
    FOREIGN KEY (TenDangNhap) REFERENCES dbo.TAIKHOAN(TenDangNhap)
)
GO

-- Bảng 4: DANHMUCDOAN
CREATE TABLE DANHMUCDOAN
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TenDanhMuc NVARCHAR(100) NOT NULL UNIQUE
)
GO

-- Bảng 5: DOAN
CREATE TABLE DOAN
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TenMon NVARCHAR(100) NOT NULL,
    IDDanhMuc INT NOT NULL,
    Gia FLOAT NOT NULL DEFAULT 0,
    FOREIGN KEY (IDDanhMuc) REFERENCES dbo.DANHMUCDOAN(ID)
)
GO

-- Bảng 6: BANAN
CREATE TABLE BANAN
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TenBan NVARCHAR(100) NOT NULL UNIQUE,
    TrangThai NVARCHAR(50) NOT NULL DEFAULT N'Trống' -- Trống || Có người
)
GO

-- Bảng 7: HOADON
CREATE TABLE HOADON
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NgayVao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayRa DATETIME,
    IDBan INT NOT NULL,
    TrangThai INT NOT NULL DEFAULT 0, -- 0: chưa thanh toán, 1: đã thanh toán
    FOREIGN KEY (IDBan) REFERENCES dbo.BANAN(ID)
)
GO

-- Bảng 8: CHITIETHOADON
CREATE TABLE CHITIETHOADON
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    IDHoaDon INT NOT NULL,
    IDMon INT NOT NULL,
    SoLuong INT NOT NULL,
    FOREIGN KEY (IDHoaDon) REFERENCES dbo.HOADON(ID),
    FOREIGN KEY (IDMon) REFERENCES dbo.DOAN(ID),
    CONSTRAINT CHK_SoLuong CHECK (SoLuong > 0)
)
GO

-- Bảng 9: NGUYENLIEU
CREATE TABLE NGUYENLIEU
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TenNguyenLieu NVARCHAR(100) NOT NULL,
    DonViTinh NVARCHAR(50) NOT NULL,
    SoLuongTon FLOAT NOT NULL DEFAULT 0
)
GO

-- Bảng 10: DINHLUONG
CREATE TABLE DINHLUONG
(
    IDMon INT NOT NULL,
    IDNguyenLieu INT NOT NULL,
    SoLuong FLOAT NOT NULL,
    PRIMARY KEY (IDMon, IDNguyenLieu),
    FOREIGN KEY (IDMon) REFERENCES dbo.DOAN(ID),
    FOREIGN KEY (IDNguyenLieu) REFERENCES dbo.NGUYENLIEU(ID)
)
GO

--- THÊM DỮ LIỆU MẪU ---
INSERT INTO LOAITAIKHOAN (TenLoai) VALUES (N'Quản lý'), (N'Nhân viên');
INSERT INTO TAIKHOAN (TenDangNhap, MatKhau, TenHienThi, IDLoaiTaiKhoan) VALUES ('admin', '1', N'Admin', 1);
INSERT INTO TAIKHOAN (TenDangNhap, MatKhau, TenHienThi, IDLoaiTaiKhoan) VALUES ('nhanvien1', '1', N'Nhân Viên A', 2);
INSERT INTO NHANVIEN (HoTen, SoDienThoai, TenDangNhap) VALUES (N'Nguyễn Văn Quản Lý', '0987654321', 'admin');
INSERT INTO NHANVIEN (HoTen, SoDienThoai, TenDangNhap) VALUES (N'Trần Thị Nhân Viên', '0123456789', 'nhanvien1');
DECLARE @i INT = 1; WHILE @i <= 10 BEGIN INSERT INTO BANAN (TenBan) VALUES (N'Bàn ' + CAST(@i AS NVARCHAR(100))); SET @i = @i + 1; END
INSERT DANHMUCDOAN (TenDanhMuc) VALUES (N'Cà Phê'), (N'Trà Sữa'), (N'Nước Ép'), (N'Đồ Ăn Vặt');
INSERT DOAN (TenMon, IDDanhMuc, Gia) VALUES (N'Cà Phê Đen', 1, 20000), (N'Cà Phê Sữa', 1, 25000), (N'Bạc Xỉu', 1, 28000);
INSERT DOAN (TenMon, IDDanhMuc, Gia) VALUES (N'Trà Sữa Trân Châu', 2, 30000), (N'Trà Sữa Matcha', 2, 35000);
INSERT DOAN (TenMon, IDDanhMuc, Gia) VALUES (N'Nước Ép Cam', 3, 30000), (N'Nước Ép Dứa', 3, 30000);
INSERT DOAN (TenMon, IDDanhMuc, Gia) VALUES (N'Hướng Dương', 4, 15000);
GO

--------------------------------

CREATE PROC USP_Login
@userName VARCHAR(100), @passWord NVARCHAR(1000)
AS
BEGIN
    SELECT * FROM dbo.TAIKHOAN WHERE TenDangNhap = @userName AND MatKhau = @passWord
END